### ISSUE TITLE
Segmentation fault after installing GCC-C++ 9.2.0-2

### ISSUE THREAD

**Issue by hind-most** [bitwiseworks/hunspell-os2#1]
Segmentation fault in Hunspell 1.7.0-1 following installation of GCC-C++ 9.2.0-2

Trap report attached
[0254_01.zip](https://github.com/bitwiseworks/hunspell-os2/files/4214207/0254_01.zip)

**Comment by SilvanScherrer** [comment]
Please try the just uploaded rpm from exp repo. It should fix it.

**Comment by hind-most** [comment]
It no longer segfaults, now I'm getting a SYS2070 
[POPUPLOG.zip](https://github.com/bitwiseworks/hunspell-os2/files/4219620/POPUPLOG.zip)

**Comment by hind-most** [comment]
A reboot was required, apologies for the noise.

**Comment by SilvanScherrer** [comment]
yes if someone hold the old dll you need to reboot. Good it's fixed.
